openapi: 3.0.1
info:
  title: Stock Management API
  version: 1.0.0
  description: API for managing stocks and purchase prices

servers:
  - url: http://localhost:8080/api

paths:
  /stock:
    $ref: './paths/stock.yaml#/stock'
  /stock/{id}:
    $ref: './paths/stock.yaml#/stockById'
  /customer:
    $ref: './paths/customer.yaml#/customer'
  /customer/{id}:
    $ref: './paths/customer.yaml#/customerById'
  /supplier:
    $ref: './paths/supplier.yaml#/supplier'
  /supplier/{id}:
    $ref: './paths/supplier.yaml#/supplierById'
  /purchaseprice:
    $ref: './paths/purchaseprice.yaml#/purchasePrice'
  /purchaseprice/{id}:
    $ref: './paths/purchaseprice.yaml#/purchasePriceById'
  /sellingprice:
     $ref: './paths/sellingprice.yaml#/sellingPrice'
  /sellingprice/{id}:
     $ref: './paths/sellingprice.yaml#/sellingPriceById'
  /stockpurchase:
    $ref: './paths/stockpurchase.yaml#/stockPurchase'
  /stockpurchase/{id}:
    $ref: './paths/stockpurchase.yaml#/stockPurchaseById'
components:
  schemas:
    Stock:
      $ref: './components/schemas/Stock.yaml'
    Customer:
      $ref: './components/schemas/Customer.yaml'
    Supplier:
      $ref: './components/schemas/Supplier.yaml'
    Purchaseprice:
      $ref: './components/schemas/PurchasePrice.yaml'
    Sellingprice:
      $ref: './components/schemas/Sellingprice.yaml'
    StockPurchase:
      $ref: './components/schemas/StockPurchase.yaml'